# configs/classical_only.yaml
# Конфигурация только для классических ML моделей

project:
  name: "classical_drought_models"
  description: "Сравнение классических ML подходов"

# Наследуем базовую конфигурацию, но переопределяем модели
defaults:
  - config

# Отключаем все SOTA модели
models:
  classical:
    linear_regression:
      enabled: true
      fit_intercept: true
      normalize: false
    
    ridge:
      enabled: true
      alpha: [0.1, 1.0, 10.0, 100.0]  # Перебор альф
      cv: 5
    
    lasso:
      enabled: true  
      alpha: [0.01, 0.1, 1.0, 10.0]
      cv: 5
    
    random_forest:
      enabled: true
      n_estimators: [100, 300, 500]
      max_depth: [10, 20, None]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      random_state: 42
      n_jobs: -1
    
    xgboost:
      enabled: true
      n_estimators: [200, 500, 800]
      learning_rate: [0.01, 0.05, 0.1]
      max_depth: [6, 8, 10]
      subsample: [0.8, 0.9, 1.0]
      colsample_bytree: [0.8, 0.9, 1.0]
      random_state: 42
      n_jobs: -1
    
    gradient_boosting:
      enabled: true
      n_estimators: [100, 200, 300]
      learning_rate: [0.05, 0.1, 0.15]
      max_depth: [4, 6, 8]
      subsample: [0.8, 0.9, 1.0]
      random_state: 42
    
    support_vector:
      enabled: true
      kernel: ["rbf", "linear", "poly"]
      C: [0.1, 1.0, 10.0, 100.0]
      epsilon: [0.01, 0.1, 0.2]
      gamma: ["scale", "auto"]
  
  # Полностью отключаем SOTA
  sota:
    earthformer:
      enabled: false
    convlstm:
      enabled: false
    tft:
      enabled: false
    unet:
      enabled: false

# Расширенная валидация для классических моделей
evaluation:
  metrics:
    - "mae"
    - "rmse"
    - "r2"
    - "mape"
    - "explained_variance"
    - "max_error"
  
  cross_validation:
    enabled: true
    type: "time_series"
    n_splits: 5
    test_size: 0.2
  
  # Feature importance анализ
  feature_analysis:
    enabled: true
    methods: ["permutation", "shap", "built_in"]
    save_plots: true

hyperparameter_optimization:
  enabled: true
  method: "grid_search"  # Для классических моделей grid search подходит
  cv_folds: 3
  scoring: "neg_mean_absolute_error"
  n_jobs: -1
