# configs/quick_test.yaml
# Конфигурация для быстрого тестирования системы (5-10 минут)

project:
  name: "quick_drought_test"
  description: "Быстрый тест системы предсказания засухи"
  mode: "development"

# Урезанные данные для быстрого тестирования
data:
  # Сокращенный временной диапазон
  years_range: [2020, 2022]       # Только 3 года вместо 22
  
  # Один тестовый регион (США)
  regions:
    us_plains: [40, 45, -100, -95]  # Меньшая область
  
  # Пространственная подвыборка
  spatial_subset:
    enabled: true
    lat_min: 40
    lat_max: 45
    lon_min: -100
    lon_max: -95
    step: 2                        # Каждый второй пиксель
  
  # Упрощенный набор переменных
  input_variables:
    - "precipitation"
    - "temperature"
    - "spi3"                      # Только основные
  
  target_variable: "spi3"
  
  # Быстрая обработка
  preprocessing:
    quality_check: false          # Пропускаем детальную проверку
    interpolation: "nearest"      # Простая интерполяция
    validation: "basic"           # Базовая валидация

# Быстрое обучение
training:
  # Короткие последовательности
  sequence_length: 6             # Вместо 12
  prediction_horizon: 1          # Только 1 месяц вперед
  
  # Простое разделение данных
  train_years: [2020, 2021]      # 2 года
  val_years: [2022, 2022]        # 1 год  
  test_years: [2022, 2022]       # Тот же год для теста
  
  # Быстрые параметры обучения
  batch_size: 8                  # Маленький batch
  max_epochs: 5                  # Мало эпох
  learning_rate: 0.01            # Больше LR для быстрой сходимости
  early_stopping_patience: 3     # Раннее остановка
  
  # Без сложных оптимизаций
  gradient_clip_val: 5.0
  accumulate_grad_batches: 1

# Только быстрые модели
models:
  # Простые классические модели
  classical:
    linear_regression:
      enabled: true              # Самая быстрая
    
    random_forest:
      enabled: true
      n_estimators: 50           # Мало деревьев
      max_depth: 5               # Неглубокие деревья
      n_jobs: 2                  # Ограничиваем параллелизм
    
    # Отключаем медленные модели
    ridge:
      enabled: false
    xgboost:
      enabled: false
    gradient_boosting:
      enabled: false
  
  # Одна простая SOTA модель
  sota:
    # Только ConvLSTM (самая простая из SOTA)
    convlstm:
      enabled: true
      input_channels: 3           # Меньше каналов
      hidden_dims: [16, 16]       # Маленькие скрытые размеры
      kernel_size: 3
      horizon: 1
    
    # Отключаем сложные модели
    earthformer:
      enabled: false
    tft:
      enabled: false
    unet:
      enabled: false

# Быстрые вычисления
compute:
  accelerator: "auto"            # Используем что доступно
  devices: 1                     # Одно устройство
  precision: 32                  # Полная точность (быстрее на CPU)
  
  # Минимальная параллелизация
  num_workers: 2                 # Мало воркеров
  persistent_workers: false
  pin_memory: false              # Отключаем для простоты
  prefetch_factor: 1

# Упрощенная валидация
evaluation:
  # Только основные метрики
  metrics:
    - "mae"
    - "rmse"
  
  # Без кросс-валидации
  cross_validation:
    enabled: false

# Минимальная визуализация
visualization:
  create_plots: true
  plot_dpi: 150                  # Меньше DPI
  
  # Только основные графики
  plots:
    dataset_overview: true
    training_curves: true
    model_comparison: true
    predictions_analysis: false   # Пропускаем детальный анализ
    spatial_maps: false
    regional_analysis: false

# Простое логирование
logging:
  level: "WARNING"               # Меньше логов
  log_to_file: false            # Только в консоль
  
  tensorboard:
    enabled: false              # Отключаем для скорости
  
  wandb:
    enabled: false

# Минимальное сохранение
output:
  save_predictions: true
  save_models: false            # Не сохраняем модели
  save_embeddings: false
  save_attention_weights: false
  
  formats:
    predictions: "json"         # Простой формат
    metrics: "json"

# Отключаем сложные функции
performance:
  compile_models: false
  mixed_precision: false
  
  profiler:
    enabled: false

# Простые callbacks
callbacks:
  model_checkpoint:
    enabled: false              # Не сохраняем checkpoints
  
  early_stopping:
    monitor: "val_loss"
    patience: 3
    mode: "min"
  
  learning_rate_monitor:
    enabled: false

# Режим отладки
debug:
  enabled: true
  fast_dev_run: false           # Не нужно, у нас уже быстро
  limit_train_batches: 0.1      # Только 10% данных
  limit_val_batches: 0.1
  limit_test_batches: 0.1
  
  # Детекция аномалий
  detect_anomaly: false         # Отключаем для скорости
  
  # Принудительное освобождение памяти
  force_gc: true

# Временные настройки для теста
temp_settings:
  # Пропускаем загрузку тяжелых данных
  skip_heavy_downloads: true
  
  # Используем кэшированные данные если есть
  use_cached_data: true
  cache_dir: "temp_cache"
  
  # Автоочистка после теста
  auto_cleanup: true
  
  # Ограничения времени
  max_runtime_minutes: 10       # Жесткий лимит времени
  timeout_per_model_minutes: 3  # Лимит на модель

# Настройки для CI/CD
ci_mode:
  enabled: false
  github_actions: false
  docker_test: false

# Валидация конфигурации
validation:
  # Проверяем что настройки действительно для быстрого теста
  assert_quick_mode: true
  max_epochs_allowed: 10
  max_batch_size_allowed: 32
  max_data_years_allowed: 5

# Ожидаемые результаты теста
expected_results:
  # Время выполнения
  max_total_time_minutes: 10
  max_data_loading_minutes: 3
  max_training_minutes: 5
  max_evaluation_minutes: 2
  
  # Качество (не ожидаем хороших результатов на таких данных)
  min_acceptable_mae: 2.0       # Очень мягкие требования
  max_acceptable_rmse: 3.0
  
  # Успешность
  min_models_trained: 2         # Хотя бы 2 модели должны обучиться
  required_outputs:
    - "experiment_results.json"
    - "model_comparison.png"

# Сообщения для пользователя
user_messages:
  start: "🚀 Запуск быстрого теста системы (ожидается ~10 минут)"
  data_phase: "📦 Загрузка тестовых данных (урезанный набор)..."
  training_phase: "🤖 Быстрое обучение базовых моделей..."
  results_phase: "📊 Создание базового отчета..."
  success: "✅ Быстрый тест завершен! Система работает корректно."
  failure: "❌ Тест не прошел. Проверьте логи и зависимости."