model:
  name: rf
  params:
    n_estimators: 500
    max_depth: 20
data:
  cube_path: data/processed/agro_cube.zarr
  target: spi3
  train_years: [2003, 2016]
  val_years:   [2017, 2019]
  test_years:  [2020, 2024]
trainer:
  random_state: 42
  n_jobs: -1
