model:
  name: xgb
  params:
    n_estimators: 800
    learning_rate: 0.05
    max_depth: 8
    subsample: 0.8
    colsample_bytree: 0.8
    objective: reg:squarederror
    random_state: 42
    n_jobs: -1

trainer:
  early_stopping_rounds: 50

data:
  cube_path: data/processed/agro_cube.zarr
  target: spi3
  train_years: [2003, 2016]
  val_years:   [2017, 2019]
  test_years:  [2020, 2024]